// src/components/Footer/Footer.tsx
import * as React from 'react'
import styled from 'styled-components'

import { ReactComponent as Twitter } from './twitter.svg'
import { theme } from '../theme'

const Container = styled.footer`
  padding: 0.25rem;
  display: flex;
  align-items: center;
`

const Socials = styled.div`
  padding: 0.125rem 0.25rem 0;

  a {
    display: block;
    color: ${theme.colors.green[700]};
  }
`

export const Footer = () => (
  <Container>
    <div>
      made with{' '}
      <span role="img" aria-label="love">
        🧡
      </span>{' '}
      in London -{' '}
    </div>
    <Socials>
      <a
        href="https://twitter.com/emoji_of_the"
        target="_blank"
        rel="noopener noreferrer"
      >
        <Twitter width="1.5rem" />
      </a>
    </Socials>
  </Container>
)

// src/lib/components/Footer/Footer.svelte
<script lang="ts">
	import YouTubeIcon from '$lib/icons/youtube.svg?component'
	import GitHubIcon from './github.svg?component'
	import DiscordIcon from './discord.svg?component'
	import PulsingHeart from './PulsingHeart.svelte'
</script>

<footer class="flex items-center justify-center gap-2 py-2">
	<div class="flex shrink-0 items-center justify-center gap-2">
		Made with
		<PulsingHeart />
		by <a href="https://magrippis.com">jmagrippis</a>
	</div>

	<a
		href="https://www.youtube.com/@jmagrippis"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="YouTube"
		class="hover:text-emphasis-hover"
	>
		<YouTubeIcon title="Johnny’s YouTube channel" class="w-5" />
	</a>
	<a
		href="https://github.com/jmagrippis/emoji-of-the-x"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="checkout the source code at the github repo"
		class="hover:text-emphasis-hover"
	>
		<GitHubIcon class="w-5" />
	</a>
	<a
		href="https://discord.gg/eR5Q52Sfm3"
		target="_blank"
		rel="noopener noreferrer"
		aria-label="Join Johnny's Discord community!"
		class="hover:text-emphasis-hover"
	>
		<DiscordIcon class="w-5" />
	</a>
</footer>
